language: scala

scala:
 - 2.10.5
 
jdk:
 - oraclejdk8
 
branches:
 only:
  - master
  - hotfix-0.4.1

sudo: false

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
  
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
 email:
  recipients:
   - vlad@uralian.com
   
script:
 - sbt -J-XX:MaxPermSize=1024m -J-Xmx2048m clean coverage test
 
after_success: 
 - sbt coveralls
